[tools]
go = "latest"
python = "latest"
uv = "latest"
bun = "latest"
protoc = "latest"
chezmoi = "latest"
node = "latest"
typst = "latest"
claude = "latest"
[settings]
trusted_config_paths = ['/workspaces/mictlan']
